
default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: postgres
  password: 18012001
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Zens_task

test:
  <<: *default
  database: Zens_task

production:
  <<: *default
  # database: <%= ENV['POSTGRES_DB'] %>
  database: Zens_task_production
  username: postgres
  password: 18012001
